# -*- coding: utf-8 -*-
"""getvideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xYIviRjBcduWCGORCPXCU_BL-lSgUSQ3
"""

import requests

API_KEY = 'FT5wLemOnkgMcOU2cdSLxmUP30oX2b9l9Tb7ZkpEWigWvf3FtGmW6VXX'
SEARCH_TERM = 'dance'

def download_first_video(search_term, api_key):
    url = f'https://api.pexels.com/videos/search?query={search_term}&per_page=1'  # Pexels API endpoint
    headers = {'Authorization': api_key}
    response = requests.get(url, headers=headers).json()
    print(response)
    video_url = response['videos'][0]['video_files'][0]['link']

    video_response = requests.get(video_url)
    if video_response.status_code == 200:
        with open('/content/sample_data/downloaded_video.mp4', 'wb') as f:
            f.write(video_response.content)
        print('Video downloaded successfully.')
    else:
        print('Failed to download video.')

download_first_video(SEARCH_TERM, API_KEY)

